### ISSUE TITLE
Dates are now in different units

### ISSUE THREAD

**Issue by Pezmc** [cfinke/OSX-Messages-Exporter#1]
It seems, at least in macOS High Sierra that dates have increased in size by a factor of 10.

For example: 

- 2017-10-18 10:29:34, is now stored as 530011774000000000.
- To get the true time, you need to divide by 1000000000
 - And then add 2001-01-01 in UNIX time (978307200).

i.e.

- 530011774000000000 / 1000000000 = 530011774
- 530011774 + 978307200 = 1508318974
- 1508318974 => Wednesday, 18 October 2017 09:29:34

**Comment by cfinke** [comment]
Fixed in 26ba2571a6a26d303aada17778c965435b18b85b
