### ISSUE TITLE
Feature Request: Split HTML by day

### ISSUE THREAD

**Issue by john-catalano** [cfinke/OSX-Messages-Exporter#10]
Before macOS borked the chat file concept, I simply exported each file to PDF. So, I'm quite happy to come across this project and tickled at how well it works, especially how it preserves attachments.

I archive my correspondence - like exported emails, birthday cards, letters (not that I get those anymore, but scanned copies of them) - by yyyy-mm-dd $person, et al.

Done this way, in a single directory, the order provides a nice context of conversations with people over time.

Please add an option to split by date.

Re. attachments, it would be nice if the folder matched the related chat name and included the attachments. For example:

2021-06-04 Joey Joe Joe.html
2021-06-04 Joey Joe Joe (folder)

**Comment by cfinke** [comment]
Fixed in 26d749511b52f5476c0861a82b5b3cff7654d549. To get daily exports, use this setting:

`--path-template "%Y-%m-%d _CHAT_TITLE_"`
