### ISSUE TITLE
Participant names missing

### ISSUE THREAD

**Issue by john-catalano** [cfinke/OSX-Messages-Exporter#11]
The example.html file shows the names of the chatters on both sides. Using this new version, I do not see any names in the resulting HTML files.

The file names do contain the participants, and the export by day (y-m-d) works just fine (thanks)>

**Comment by cfinke** [comment]
Names are only shown in conversations with more than two people. Are you looking at 2-person chats or group chats?

**Comment by john-catalano** [comment]
I wasn't looking at 3+ person chats. But, I did check some of those and you are correct - the names of the people are displayed. Thank you.
