### ISSUE TITLE
Timezone offset is off by 4 hours for America/New_York

### ISSUE THREAD

**Issue by eliransapir** [cfinke/OSX-Messages-Exporter#12]
Timezone offset is off by 4 hours for America/New_York, for some reason, i can't figure out why the TZ offset is not working at all...

**Comment by cfinke** [comment]
I can't reproduce this. Can you paste the exact command you're running here?  With this:

`
/Users/cfinke/projects/OSX-Messages-Exporter/messages-exporter.php -o /Users/cfinke/Desktop/test/ --date-start 2021-10-01 --timezone "America/New_York"
`

it shows all times shifted forward three hours (as my real timezone is America/Los_Angeles).
