### ISSUE TITLE
Feature Request - Option to target one conversation. 

### ISSUE THREAD

**Issue by windhamdavid** [cfinke/OSX-Messages-Exporter#18]
Thank you for publishing this. I think one helpful feature would be the option to target one conversation.  I'm wondering if you've already looked into adding that option before I dive into the database and script?

**Comment by cfinke** [comment]
That's not currently possible, but it does seem like a reasonable improvement to make.

**Comment by cfinke** [comment]
Now you can target an individual conversation with either the --match or --match_regex arguments. e.g.,

`php messages-exporter.php --match "Sam"`

will match any conversation whose title includes "Sam".

`php messages-exporter.php --match_regex "/^Sam$/"`

will match any conversation whose title is exactly "Sam".
