### ISSUE TITLE
New Install with Library Not Loading

### ISSUE THREAD

**Issue by brandonflatsoda** [cfinke/OSX-Messages-Exporter#24]
I'm getting the following error when running
     php messages-exporter.php -o ~/Desktop/Messages/

for the first time.

Library not loaded: '/usr/local/opt/libtiff/lib/libtiff.5.dylib'
  Referenced from: '/usr/local/Cellar/gd/2.3.3_4/lib/libgd.3.dylib'
  Reason: tried: '/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file), '/usr/local/Cellar/libtiff/4.6.0/lib/libtiff.5.dylib' (no such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file)
Abort trap: 6

**Comment by cfinke** [comment]
I think this must be an issue with your PHP installation. You could try finding libtiff.5.dylib somewhere and putting it at /usr/local/opt/libtiff/lib/, but that's just my best guess. In any case, it's not an issue specific to OSX-Messages-Exporter.

**Comment by brandonflatsoda** [comment]
I think I ended up updating brew to get it working. Thank you for closing this out, I went to find the issue to remove it after I got that updated but couldn't find it again.
