### ISSUE TITLE
Is this supposed to auto grab contact Names?

### ISSUE THREAD

**Issue by invious** [cfinke/OSX-Messages-Exporter#3]
All my folders are in phone numbers, I can't quite read the PHP, is it trying to map phone numbers to contacts? If so it's not working for me

**Comment by cfinke** [comment]
Yes, it should automatically use contact names, but only if they're in your Mac's local address book.  For best results, open your Contacts app and drag all contacts from the iCloud section to the "On My Mac" section before running it.
