### ISSUE TITLE
Unable to Open Database

### ISSUE THREAD

**Issue by ilovemetalrobots** [cfinke/OSX-Messages-Exporter#4]
I'm running from the command line on Catalina 10.15.3. Any ideas how to remedy this error? Thank you!

Fatal error: Uncaught Exception: Unable to open database: unable to open database file in /Users/kbb/Desktop/OSX-Messages-Exporter-master/messages-exporter.php:68
Stack trace:
#0 /Users/kayneburk/Desktop/OSX-Messages-Exporter-master/messages-exporter.php(68): SQLite3->__construct('/Users/kbb...', 1)
#1 {main}
  thrown in /Users/kbb/Desktop/OSX-Messages-Exporter-master/messages-exporter.php on line 68

**Comment by cfinke** [comment]
It looks like it might be because Terminal doesn't have Full Disk Access.  See this for instructions on doing so: https://www.tech-otaku.com/mac/manually-granting-applications-full-disk-access-macos-catalina/
