### ISSUE TITLE
Feature suggestion: split html by year

### ISSUE THREAD

**Issue by omueller** [cfinke/OSX-Messages-Exporter#9]
Thanks a lot for this great tool, it works exactly as expected, even with a quite large iMessage history (~35GB). 

I just have a small suggestion:  for some large and old chats (over 10 years of messages), it would be nice to have an option to have an automatic split by year for example, so example_2009.html, example_2010.html, etc, as even Safari is having some issues displaying a 15MB large archive file.  

(a workaround would be to use --date-start + --date-stop and an some shell lines to have this too, but an integrated option would be simpler). 

Best regards & merci encore!

**Comment by john-catalano** [comment]
Funny you should ask this. I actually emailed cfinke a similar request, last week. Your post inspired me to add it, here.

**Comment by cfinke** [comment]
I think what I'm going to do is add a command-line option for the chat filename that supports all of the `strftime` formatting strings for dates, so you could export daily chats by doing something like `--filename-prefix="%Y-%m-%d"` or yearly chats with `--filename-prefix="%Y"`

**Comment by cfinke** [comment]
Fixed in 26d749511b52f5476c0861a82b5b3cff7654d549. To get yearly exports, use this setting:

`--path-template "_CHAT_TITLE_%Y"`
